apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: lab
servers: 1
agents: 2
image: rancher/k3s:v1.35.5-k3s1
ports:
  - port: 80:80
    nodeFilters: [loadbalancer]
  - port: 443:443
    nodeFilters: [loadbalancer]
registries:
  create:
    name: k3d-lab-registry.localhost
    host: "127.0.0.1"
    hostPort: "5003"
    volumes:
      - lab-registry-data:/var/lib/registry
