apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: lab
servers: 1
agents: 2
image: rancher/k3s:TAG
ports:
  - port: 80:80
    nodeFilters: [loadbalancer]
  - port: 443:443
    nodeFilters: [loadbalancer]
registries:
  create:
    name: k3d-lab-registry.localhost
    host: "0.0.0.0"
    hostPort: "5001"
